webghome/hexanhome/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('hexanhome.views',
	url(r'^$', 'index'),
    url(r'^home/$', 'home'),
    url(r'^profil/$', 'profil'),
    url(r'^profil/piece/(?P<piece_name_url>\w+)/$', 'piece'),
    url(r'^config/$','config'),
    url(r'^config/AjoutPiece/$','AjoutPiece'), 
    url(r'^config/AjoutActionneur/$','AjoutActionneur'), 
    url(r'^config/AjoutCapteur/$','AjoutCapteur'), 	
    url(r'^login/$', 'login_view'),
    url(r'^logout/$', 'logout_view'),
    url(r'^register/$','register'),
    url(r'^profil/settings/(?P<profil_name_url>\w+)/$','settings'),
    url(r'profil/Ajouter_Profil/$','AjouterProfil'),
    #URLS DE L'API
    url(r'login_client/$','login_client'),
    url(r'test_profiles/$','test_profiles'),
    url(r'^config/AjoutActionneur/learning/(?P<actionneur_id>\w+)/$','learning'),   
    url(r'action/$','action'),
    url(r'regle/$','regle'),


)

webghome/webghome/urls.py
from django.conf.urls import patterns, include, url
from hexanhome.models import Piece
from django.contrib import admin
admin.autodiscover()

# from hexanhome.views import HomeView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webghome.views.home', name='home'),

    url(r'^admin/', include(admin.site.urls)),
    # url(r'^home/$', HomeView.as_view(), name='home'),	
    url(r'^', include('hexanhome.urls')),	

)

webghome/hexanhome/models.py
# coding=UTF-8

from django.db import models
from django.contrib.auth.models import User
from django.utils.http import urlquote
from django.utils.translation import ugettext_lazy as _
from django.core.mail import send_mail
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
import home_watcher
from actionneur_learning import *

class CustomUserManager(BaseUserManager):

	def _create_user(self, email, password,
					 is_staff, is_superuser, **extra_fields):
		"""
		Creates and saves a User with the given email and password.
		"""
		if not email:
			raise ValueError('The given email must be set')
		email = self.normalize_email(email)
		user = self.model(email=email,is_staff=is_staff, is_active=True,is_superuser=is_superuser, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_user(self, email, password=None, **extra_fields):
		return self._create_user(email, password, False, False,
								 **extra_fields)

	def create_superuser(self, email, password, **extra_fields):
		return self._create_user(email, password, True, True,
								 **extra_fields)



class CustomUser(AbstractBaseUser, PermissionsMixin):
	"""
	A fully featured User model with admin-compliant permissions that uses
	a full-length email field as the username.

	Email and password are required. Other fields are optional.
	"""
	email = models.EmailField(_('email address'), max_length=254, unique=True)
	ip_adress = models.URLField(blank = True)
	first_name = models.CharField(_('first name'), max_length=30, blank=True)
	last_name = models.CharField(_('last name'), max_length=30, blank=True)
	is_staff = models.BooleanField(_('staff status'), default=False,
		help_text=_('Designates whether the user can log into this admin '
					'site.'))
	is_active = models.BooleanField(_('active'), default=True,
		help_text=_('Designates whether this user should be treated as '
					'active. Unselect this instead of deleting accounts.'))
	objects = CustomUserManager()

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	class Meta:
		verbose_name = _('user')
		verbose_name_plural = _('users')

	def get_absolute_url(self):
		return "/users/%s/" % urlquote(self.email)

	def get_full_name(self):
		"""
		Returns the first_name plus the last_name, with a space in between.
		"""
		full_name = '%s %s' % (self.first_name, self.last_name)
		return full_name.strip()

	def get_short_name(self):
		"Returns the short name for the user."
		return self.first_name

	def get_email(self):
		return self.email

	def email_user(self, subject, message, from_email=None):
		"""
		Sends an email to this User.
		"""
		send_mail(subject, message, from_email, [self.email])

	def set_ip(self,ip):
		self.ip_adress = ip
		self.save()
		return True

class Type(models.Model):
	"""le type de la valeur renvoyé par le capteur : temperateur, allumé/éteint, etc ..."""
	id = models.AutoField(primary_key=True)
	nom = models.CharField(max_length=200)	
	def __unicode__(self):
		return unicode(self.nom)

class Piece(models.Model):
	"""Piece dans laquelle se trouve le Capteur/Actionneur"""
	id = models.AutoField(primary_key=True)
	nom = models.CharField(max_length=200)	
	url= models.CharField(max_length=200)
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	def __unicode__(self):
		return unicode(self.nom)	

class Capteur(models.Model):
	"""Classe permettant de representer un Capteur"""
	id = models.AutoField(primary_key=True)
	nom = models.CharField(max_length=200 , blank=True)
	#foreign key vers les pieces
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	id_piece = models.ForeignKey(Piece,null = True, blank = True)
	identifiant = models.CharField(max_length=8)
	typeCapteur_CHOICES = (
		('D','detecteur de presence et de luminosite'),
		('F','Contact de fenetre'),
		('C','Capteur temperature')	
	)
	capteurtype = models.CharField(max_length=1, choices=typeCapteur_CHOICES)
	def __unicode__(self):
		return unicode(self.nom)

class Actionneur(models.Model):
	"""Classe permettant de representer un Actionneur"""
	id = models.AutoField(primary_key=True)
	nom = models.CharField(max_length=200)
	#foreign key vers les pieces
	id_piece = models.ForeignKey(Piece)
	trame_on = models.CharField(max_length=28)
	trame_off = models.CharField(max_length=28)
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	identifiant = models.CharField(max_length=8)
	def __unicode__(self):
		return unicode(self.nom) 

class Attribut(models.Model):
	"""Pour si un capteur renvoie plusieurs type de valeurs"""
	id = models.AutoField(primary_key=True)
	nom = models.CharField(max_length=200)
	valeur = models.IntegerField(blank = True,null = True)
	#foreign key vers les type
	id_type = models.ForeignKey(Type,blank = True, null = True)
	identifiant = models.CharField(max_length=8)
	def __unicode__(self):
		return unicode(self.nom)

class Attr_Capteur(models.Model):
	"""Pour si un capteur renvoie plusieurs type de valeurs"""
	id = models.AutoField(primary_key=True)
	#foreign key vers les type
	id_type = models.ForeignKey(Type,blank = True, null = True)
	#foreign key vers les capteurs
	id_capt = models.ForeignKey(Capteur)
	#foreign key vers les Attributs
	id_attr = models.ForeignKey(Attribut)
	def __unicode__(self):
		return unicode(self.id_capt)


class RuleProfile(models.Model):
	"""docstring fos RuleProfile"""
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	nom = models.CharField(max_length=200)
	url = models.CharField(max_length=200)
	def __unicode__(self):
		return unicode(self.nom)

	def test_and_execute(self):
		watcher = home_watcher.HomeWatcher()
		for rule in self.presencerule_set.all():
			if not rule.is_verified(watcher.getPresence(rule.idCapteur.identifiant)):
				return False
		for rule in self.timerule_set.all():
			if not rule.is_verified(watcher.getTime()):
				return False
		for rule in self.temperaturerule_set.all():
			if not rule.is_verified(watcher.getTemperature(rule.idCapteur.identifiant)):
				return False
		for rule in self.weatherrule_set.all():
			if not rule.is_verified(watcher.getWeatherCondition()):
				return False
		for rule in self.weekdayrule_set.all():
			if not rule.is_verified(watcher.getWeekday()):
				return False

		for action in self.ruleaction_set.all():
			action.execute_action()

		return True

class RuleAction(models.Model):
	"""docstring fos RuleAction""" 
	# action doit etre 'on' ou 'off'
	action = models.CharField(max_length=200)
	profil = models.ForeignKey(RuleProfile)
	actionneur = models.ForeignKey(Actionneur)
	
	def execute_action(self):
		if self.action == 'on':
			sendTrameToServer([self.actionneur.trame_on])
		elif self. 	action == 'off':
			sendTrameToServer([self.actionneur.trame_off])

class PresenceRule(models.Model):
	profil = models.ForeignKey(RuleProfile)
	isPresent = models.BooleanField()
	idCapteur = models.ForeignKey(Capteur)
	
	def is_verified(self, actual_presence):
		return self.isPresent == actual_presence

class TimeRule(models.Model):
	"""docstring for TimeRule"""
	profil = models.ForeignKey(RuleProfile)
	start_time = models.CharField(max_length=200)
	end_time = models.CharField(max_length=200)

	def is_verified(self, time):
		heuredebut = int(self.start_time.replace(':',''))
		heurefin = int(self.end_time.replace(':',''))
		actual_time = int(time.replace(':',''))
		if heuredebut < heurefin :
			return heuredebut < actual_time < heurefin
		else:
			return (heuredebut < actual_time < 24) or (0 < actual_time < heurefin)

class TemperatureRule(models.Model):
	profil = models.ForeignKey(RuleProfile)
	idCapteur = models.ForeignKey(Capteur)
	temperatureValue = models.IntegerField()
	isMinimum = models.BooleanField()

	def is_verified(self, actual_temp):
		if self.isMinimum:
			return actual_temp < self.temperatureValue
		else:
			return actual_temp > self.temperatureValue


class WeatherRule(models.Model):
	profil = models.ForeignKey(RuleProfile)
	weatherCondition = models.CharField(max_length=200)
	"""docstring for WeatherRule"""


	def is_verified(self, weatherCondition):
		return self.weatherCondition == weatherCondition

class WeekdayRule(models.Model):
	profil = models.ForeignKey(RuleProfile)
	Jour_CHOICES = (
		('0','Lundi'),
		('1','Mardi'),
		('2','Mercredi'),
		('3','Jeudi'),
		('4','Vendredi'),
		('5','Samedi'),
		('6','Dimanche')	
	)
	weekday = models.CharField(max_length=1, choices=Jour_CHOICES)
	"""docstring for WeekdayRule"""


	def is_verified(self, weekDay):
		return int(self.weekday) == weekDay

webghome/hexanhome/forms.py
from django import forms
from hexanhome.models import *
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class PieceForm(forms.ModelForm):
    nom = forms.CharField(max_length=128, help_text= "Ajouter le nom de la piece")

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Piece

class ActionneurForm(forms.ModelForm):
    nom= forms.CharField(max_length=200, help_text="Ajouter le nom de l'actionneur")
    valeur =forms.BooleanField(required=False)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Actionneur

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    username = forms.CharField(widget = forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget = forms.EmailInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class CustomUserCreationForm(UserCreationForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """
    email = forms.CharField(widget = forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Mot de passe')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='Confirmer mot de passe')
    def __init__(self, *args, **kargs):
        super(CustomUserCreationForm, self).__init__(*args, **kargs)
        del self.fields['username']

    class Meta:
        model = CustomUser
        fields = ("email",)

class CustomUserChangeForm(UserChangeForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """

    def __init__(self, *args, **kargs):
        super(CustomUserChangeForm, self).__init__(*args, **kargs)
        del self.fields['username']

    class Meta:
        model = CustomUser

webghome/hexanhome/templates/hexanhome/AjoutAction.html
{% if listActionneur %}
<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Ajout d'une action</h3>
	</div>
	<div class="panel-body">
		<SELECT class="form-control" name="nomActionneur" id="nomActionneur"  size="1">
		{% for actionneur in listActionneur %}
			<OPTION >{{actionneur.nom}}
		{%endfor%}
		</SELECT>
		<input type="radio" name="action" value="on"> Allumer
		<input type="radio" name="action" value="off" checked> Eteindre
		</br>
		<input type="submit" value="Entrer" name="AjouterAction" class="btn btn-default">
	</div>	
</div>
{%endif%}	

webghome/hexanhome/templates/hexanhome/AjoutActionneur.html
{% extends "base.html" %}
{% block title %}Ajout Actionneur{% endblock %}
{% block content %}
<h1>Ajout d'un actionneur:</h1>
<form id="category_form" method="post" action="/config/AjoutActionneur/">
    {% csrf_token %}
        <div class="form-group {%if erreurID %}has-error {%endif%} has-feedback">
            <label>Nom</label>
            <input type="text" class="form-control" name="NomActionneur" id="nameActionneur" placeholder="Enter nom">
            {%if erreurID  %}
                <span class="glyphicon glyphicon-remove form-control-feedback"></span>
                <span class="help-block">{{erreurID}}</span>
            {%endif%}
        </div>
    {% if pieces %}
    <div class="form-group">
        <label>Pièce</label>
        <SELECT class="form-control" name="nomPiece" size="1">
            {% for piece in pieces %}
                <OPTION>{{ piece.nom }}
            {% endfor %}
        </SELECT>
    </div>
    {% endif %}
    <input type="submit" value="Valider" name="AjoutActionneur"  class="btn btn-default">
</form>

{% endblock %}

webghome/hexanhome/templates/hexanhome/AjoutCapteur.html
{% extends "base.html" %}
{% block title %}Ajout Capteur{% endblock %}
{% block header%}
	<script language="JavaScript">
	  function Lien()
	  {
		optionSelect = document.formulaire.numeroIdentifiant.selectedIndex;
		numCapteur=document.formulaire.numeroIdentifiant.options[optionSelect].value;
		champNom=document.formulaire.NomCapteur;
		champNom.imput.value=nomCapteur;
	  }

	</script>
{% endblock %}
{% block content %}
	<h1>Ajout d'un capteur:</h1>
	<form id="category_form" name="formulaire" method="post" action="/config/AjoutCapteur/">
		{% csrf_token %}
		<div class="form-group">
			<label>Nom</label>
			<input type="text" class="form-control" name="NomCapteur" id="nomCapteur" placeholder="Enter nom">
		</div>
		{% if pieces %}
			<div class="form-group">
				<label>Pièce</label>
				<SELECT class="form-control" name="nomPiece" size="1">
					{% for piece in pieces %}
						<OPTION>{{ piece.nom }}
	  				{% endfor %}
	  			</SELECT>
	  		</div>
	  	{% endif %}
	  	{% if typeCapteur_CHOICES %}
			<div class="form-group">
				<label>Type</label>
				<SELECT class="form-control" name="capteurtype" size="1">
					{% for typecapteur in typeCapteur_CHOICES %}
						<OPTION value="{{typecapteur.0}}" >{{ typecapteur.1}}
	  				{% endfor %}
	  			</SELECT>
	  		</div>
	  	{% endif %}	
	      <div class="form-group {%if erreurID %}has-error {%endif%} has-feedback">
	        <label class="control-label"  for="numeroIdentifiant">Identifiant</label>
	        <input type="text" class="form-control " name="numeroIdentifiant" id="numeroIdentifiant" placeholder="Enter identifiant">
	        {%if erreurID %}
	       		<span class="glyphicon glyphicon-remove form-control-feedback"></span>
	        	<span class="help-block">{{erreurID}}</span>
	        {%endif%}
	      </div>
		<input type="submit" value="Valider" name="AjoutCapteur"  class="btn btn-default">
	</form>

{% endblock %}

webghome/hexanhome/templates/hexanhome/AjoutPiece.html
{% extends "base.html" %}
{% block title %}Ajout Pièce{% endblock %}
{% block content %}
	<h1>Ajout d'une pièce:</h1>
	<form id="category_form" method="post" action="/config/AjoutPiece/">
	 	{% csrf_token %}
	  	<div class="form-group {%if erreur %}has-error {%endif%} has-feedback">
			<label class="control-label" for="NomPiece">Nom</label>
			<input type="text" class="form-control" name="NomPiece" id="NomPiece" placeholder="Enter nom">
			{%if erreur %}
	       		<span class="glyphicon glyphicon-remove form-control-feedback"></span>
	        	<span class="help-block">{{erreur}}</span>
	        {%endif%}
	  	</div>
		<input type="submit" value="Entrer"  class="btn btn-default">
  </form>
{% endblock %}

webghome/hexanhome/templates/hexanhome/config.html
{% extends "base.html" %}
{% block title %}Config{% endblock %}
{% block content %}
<h3>Ajout d'une pièce:</h3>
<a class="btn btn-default"  href="/config/AjoutPiece">Ajout d'une pièce</a>
<h3>Ajout d'un capteur:</h3>
<a class="btn btn-default"  href="/config/AjoutCapteur" {%if not piece_list%}disabled="disabled"{%endif%}>Ajout d'un capteur </a>
<h3>Ajout d'un actionneur:</h3>
<a class="btn btn-default"  href="/config/AjoutActionneur" {%if not piece_list%}disabled="disabled"{%endif%}>Ajout d'un actionneur</a>
{% endblock %}

webghome/hexanhome/templates/hexanhome/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
	{% if user.is_authenticated %}
        <div class="row" >

            {% for piece in user.piece_set.all%}
                <div class="{%if user.piece_set.all.count == 1%}col-md-12{%else%}col-md-6 {%endif%}">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{piece.nom}}</h3>
                        </div>
                        <div class="panel-body">
                            <div class="row" >
                                {% for capteur in piece.capteur_set.all%}
                                        <div class="col-md-6">
                                             <div class="panel panel-primary">
                                                <div class="panel-heading">
                                                    <h3 class="panel-title">{{capteur.nom}}</h3>
                                                </div>
                                                <div class="panel-body">
                                                    <div id="capteurAffichage">
                                                        {% for capteurvalue in capteur.attr_capteur_set.all%}
                                                            <h4>{{capteurvalue.id_attr}} :</h4>
                                                            {% if capteurvalue.id_attr.nom == 'contact' or 'presence' %}
                                                                {% if capteurvalue.id_attr.valeur == 1 %}
                                                                    <h5>Oui</h5>
                                                                {% elif capteurvalue.id_attr.valeur == 0 %}
                                                                    <h5>Non</h5>
                                                                {% else %}
                                                                    <h5>{{ capteurvalue.id_attr.valeur }}</h5>
                                                                {% endif%}
                                                            {%endif%}
                                                            {% if capteurvalue.id_attr.nom == 'contact' %}
                                                                    </br>
                                                                    </br>
                                                                    </br>
                                                             {% elif capteurvalue.id_attr.nom == 'temperature' %}
                                                                    </br>
                                                                    </br>
                                                                    </br>
                                                            {% endif%}
                                                        {% endfor %}
                                                    </div>
                                                    </br>
                                                    <form id="category_form" method="post" action="/home/">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="capteur_identifiant" value="{{capteur.identifiant}}">
                                                        <button type="submit" name="Supp_capteur"class="btn btn-danger btn-xs ">Supprimer Capteur</button>
                                                    </form>
                                                </div>
                                             </div>
                                        </div>
                                {% endfor %}
                            {% for actionneur in piece.actionneur_set.all%}
                                    <div class="col-md-6">
                                         <div class="panel panel-primary">
                                            <div class="panel-heading">
                                                <h3 class="panel-title">{{actionneur.nom}}</h3>
                                            </div>
                                            <div class="panel-body">
                                                </br>
                                                    <div class="form-inline">
                                                         <form id="actionneur_form" method="post" action="/home/">
                                                                 {% csrf_token %}
                                                                <input type="hidden" name="actionneur_id1" value="{{actionneur.id}}">
                                                                <button type="submit" name="Actionner" class="btn btn-primary btn-xs  "> Allumer </button>
                                                       
                                                                <input type="hidden" name="actionneur_id2" value="{{actionneur.id}}">
                                                                <button type="submit" name="Eteindre" class="btn btn-primary btn-xs  ">Eteindre</button>
                                                      
                                                                 {% csrf_token %}
                                                                <input type="hidden" name="actionneur_id" value="{{actionneur.id}}">
                                                                <button type="submit" name="Learning" class="btn btn-primary btn-xs  ">Learning</button>

                                                        </form>
                                                    </div>
                                                </br>
                                                <form id="category_form" method="post" action="/home/">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="actionneur_identifiant" value="{{actionneur.identifiant}}">
                                                    <button type="submit" name="Supp_actionneur"class="btn btn-danger btn-xs ">Supprimer Actionneur</button>
                                                </form>
                                            </div>
                                         </div>
                                    </div>
                            {% endfor %}
                        </div>
                            <form id="category_form" method="post" action="/home/">
                               {% csrf_token %}
                                <input type="hidden" name="piece_nom" value="{{piece.nom}}">
                                <button type="submit" name="Supp_piece"class="btn btn-danger btn-xs ">Supprimer pièce</button>
                            
                                <a id="lettre_{{lettre}}" href="/config/AjoutCapteur/" type="button" class="btn btn-default btn-xs">Ajouter Capteur</a>
                                <a id="lettre_{{lettre}}" href="/config/AjoutActionneur/" type="button" class="btn btn-default btn-xs">Ajouter Actionneur</a>
                            </form>
                       </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if weather != ' '%}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Météo</h3>
                </div>
                <div class="panel-body">
                    <div class="row" >
                        <div class="col-md-8">
                            <h3  style="display:table-cell; vertical-align:middle;">Temperature: {{weather.current_temp}}&deg;C </h3>
                        </div>
                        <div class="col-md-4">
                            <p style ="vertical-align:middle;">    Description: {{weather.description}} </p>
                        </div>
                    </div>
                   

                </div>
            </div>
            {% endif%}
    {% endif %}
{% endblock %}

webghome/hexanhome/templates/hexanhome/learning.html
{% extends "base.html" %}
{% block title %}Learning {{actionneur.nom}}{% endblock %}
{% block content %}
<h3>Initialiser l'actionneur</h3>
	<h4>Afin de configurer l'actionneur il faut appuyer sur le bouton learning de l'actionneur, puis appuyer sur le bouton envoie de trame  <h4>
	<form id="category_form" method="post" action="/config/AjoutActionneur/learning/{{actionneur.id}}/">
        {% csrf_token %}
        <input type="hidden" name="actionneur_identifiant" value="{{actionneur.id}}">
        <button type="submit" name="Supp_capteur" class="btn btn-default  ">Envoie de Trame</button>
    </form>
{% endblock %}

webghome/hexanhome/templates/hexanhome/login.html
{% extends "base.html" %}
{% block title %}Log in{% endblock %}
{% block head %}Log in{% endblock %}
{% block content %}
    {% if form.has_errors %}
    <p> Username or password didn't work. Please enter them again </p>
    {% endif %}

    <section>
   {% if erreur %}
        <div class="alert alert-danger">Your username and/or password were incorrect!</div>
    {% endif %}

    <form method="post" action=".">
      {% csrf_token %}
      <p>
        <label for="id_email">Email:</label>
        <input type="email" class="form-control" name="email" id="email">
      </p>
      <p>
        <label for="id_password">Password:</label>
        <input type="password" class="form-control" name="password" id="password">
      </p>
      {% if next %}
        <input type="hidden" name="next" value="{{ next }}" />
      {% else %}
        <input type="hidden" name="next" value="/home/" />
      {% endif %}
      <input type="submit" value="Valider" />
    </form>
  </section>
</div>
{% endblock %}

webghome/hexanhome/templates/hexanhome/nouvel_utilisateur.html
{% extends "base.html" %}
{% block title %}Nouvel Utilisateur{% endblock %}
{% block head %}Nouvel Utilisateur{% endblock %}
{% block content %}

	{% if form.has_errors %}
	<p> Username or password didn't work. Please enter them again </p>
	{% endif %}

	<section>
	{% if form.errors %}
	  <p>Your username and password didn't match, please try again.</p>
	{% endif %}

		<form method="post" action="/nouvel_utilisateur">
			{% csrf_token %}

			{% for field in form.visible_fields %}
				<div class="form-group">
					<label >{{ field.label }}</label>
					<input type="text" class="form-control" name="{{ field.name }}" id="id_{{ field.name }}" type="password"> 
					{% if field.errors %}
						<span class="help-inline">
							{% for error in field.errors %}
							{{ error }}
							<br/> 
							{% endfor %}
						</span>

						{% if field.help_text%}
							<p class="help-block">
								{{ field.help_text}}
							</p>
						{% endif %}
					{% endif %}
				</div>
			{% endfor %}
			<input type="submit" value="Submit"  class="btn btn-default">
		</form>
	</section>


{% endblock %}

webghome/hexanhome/templates/hexanhome/profil.html
{% extends "base.html" %}
{% csrf_token %}
{% block title %}Profil{% endblock %}

{% block content %}
	{% if profil_list %}
		{% for profil in profil_list %}
		<h5 id="profilAffichage" onClick="Redirect('/profil/settings/{{ profil.url }}');" onmouseover="this.style.background='#ebebeb';" onmouseout="this.style.background='white'; ">{{profil.nom}}</h5>
		{% endfor %}
	{% endif%}
	<a class="btn btn-default btn-lg btn-block " href='/profil/Ajouter_Profil' >Ajouter Profil</a>
{% endblock %}

{% block footer%}
<script language="JavaScript">
function Redirect(url){
	window.location=url;
}
</script>

{%endblock%}

webghome/hexanhome/templates/hexanhome/signup.html
{% extends "base.html" %}
{% block title %}Creation de compte{% endblock %}
{% block head %}Creation de compte{% endblock %}
{% block content %}
    {% if form.has_errors %}
    <p> Username or password didn't work. Please enter them again </p>
    {% endif %}

    <section>
    {% if form.errors %}
      <p>Your username and password didn't match, please try again.</p>
    {% endif %}

    <form method="post" action=".">
      {% csrf_token %}
      <p>
        <label for="id_username">Username:</label>
        <input type="text" class="form-control" name="username" id="username">
      </p>
      <p>
        <label for="id_password">Password:</label>
        <input type="password" class="form-control" name="password" id="password">
      </p>
      {% if next %}
        <input type="hidden" name="next" value="{{ next }}" />
      {% else %}
        <input type="hidden" name="next" value="/home/" />
      {% endif %}
      <input type="submit" value="Valider" />
    </form>
  </section>

{% endblock %}